const commands = {
    about: ["I'm a fourth-year BA/MA student at the University of Chicago,",
        "where I study Economics, International Relations, and Critical Race and Ethnic Studies.",
        "I design policy to maximize the promise and minimize the peril of emerging technology,",
        "with particular interests in decarbonization and AI. I've previously modeled nuclear",
        "waste shipping networks for the federal government, managed the Dallas Mavericks' data", 
        "warehouse and consulted on blockchain projects with Nobel Prize-winning economists."],
    posts: ["which post...? type a key word:", "tiger", "patent", 
        "cop28", "hotdog", "kungfu", "nationalism", "mekong", "latin", "sports", 
        "transnationalism", "flight-tracker"],
    projects: ["Which project...? type a key word:", "carrots", 
        "lead-water", "green-roof", "safety", "elevator", "podcast"],
    resume: ["i once ate many bananas"],
    attack: ["yes i do"],
    defense: ["i COULD get stabbed idk"],
    speed: ["faster than a lambo"],
    type: ["meow meow meow"],
    credits: [" -- Built by Jesenia Parthasarathy, check out: https://github.com/jeseniapar",
        " -- Got the inspiration from: https://rona.wang/ and https://terminal.jcubic.pl/",
        " -- Helped with Javascript logic by fkcodes: https://www.youtube.com/watch?v=KtYby2QN0kQ",
        " -- And I learned how to build a website from this video: https://www.youtube.com/watch?v=OulQ9W2s6Z0",
    ],
    email: ["ethanj@uchicago.edu"]
};
